baseURL = "/"
languageCode = "en-us"
title = "Sellers' Dash"
theme = 'minimal'
publishDir = "docs"
[[menu.main]]
    name = "Home"
    weight = -81
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = -80
    identifier = "blog"
    url = "/blog/"